Repository voidcosmos/npkill, pull requests merged in 2019-10, with the labels that each got.

#45 Feat: delete status
  .gitignore
  __tests__/result.service.test.ts
  src/constants/messages.constants.ts
  src/controller.ts
  src/interfaces/folder.interface.ts
  src/services/results.service.ts
Labels: enhancement

#48 docs: fix typos and reformat some text
  .github/CONTRIBUTING.md
  README.MD
Labels: documentation

#49 Rename to `convertBytesToKb`, Fix help output, Fix typos
  .github/CONTRIBUTING.md
  README.MD
  src/controller.ts
  src/interfaces/file-service.interface.ts
  src/services/files.service.ts
  src/services/windows-files.service.ts
Labels: improvement
